import Head from 'next/head';
import PropTypes from 'prop-types';
import Header from '@/components/Header';
import Hero from '@/components/Hero';

const Layout = ({ title, description, image, children }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero description={description} image={image} />
        {children}
      </main>
    </>
  );
};

Layout.propTypes = {
  title: PropTypes.string.isRequired,
  description: PropTypes.string.isRequired,
  image: PropTypes.string.isRequired,
  children: PropTypes.node,
};

Layout.defaultProps = {
  children: <></>,
};

export default Layout;
